package com.zcz.www.entity;

import com.zcz.www.utils.DateUtils;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activity_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ActivityUser {
    /**
     * Database Column Remarks:
     * 活动ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     * Database Column Remarks:
     * 用户ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     * 参与活动的状态
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.join_status
     *
     * @mbg.generated
     */
    private Integer joinStatus;

    /**
     * Database Column Remarks:
     * 申请时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.activity_id
     *
     * @return the value of activity_user.activity_id
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.activity_id
     *
     * @param activityId the value for activity_user.activity_id
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.user_id
     *
     * @return the value of activity_user.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.user_id
     *
     * @param userId the value for activity_user.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.join_status
     *
     * @return the value of activity_user.join_status
     * @mbg.generated
     */
    public Integer getJoinStatus() {
        return joinStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.join_status
     *
     * @param joinStatus the value for activity_user.join_status
     * @mbg.generated
     */
    public void setJoinStatus(Integer joinStatus) {
        this.joinStatus = joinStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.create_time
     *
     * @return the value of activity_user.create_time
     * @mbg.generated
     */
    public String getCreateTime() {
        return DateUtils.getFormate(createTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.create_time
     *
     * @param createTime the value for activity_user.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "ActivityUser{" +
                "activityId=" + activityId +
                ", userId=" + userId +
                ", joinStatus=" + joinStatus +
                ", createTime=" + createTime +
                '}';
    }
}