package com.zcz.www.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Admin {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   管理员姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     * Database Column Remarks:
     *   管理员权限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_authority
     *
     * @mbg.generated
     */
    private String adminAuthority;

    /**
     * Database Column Remarks:
     *   管理员性别，未填写“0”，男“1”，女“2”
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_sex
     *
     * @mbg.generated
     */
    private Integer adminSex;

    /**
     * Database Column Remarks:
     *   管理员手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_phone
     *
     * @mbg.generated
     */
    private String adminPhone;

    /**
     * Database Column Remarks:
     *   管理员地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_adrress
     *
     * @mbg.generated
     */
    private String adminAdrress;

    /**
     * Database Column Remarks:
     *   管理员邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_email
     *
     * @mbg.generated
     */
    private String adminEmail;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_authority
     *
     * @return the value of admin.admin_authority
     *
     * @mbg.generated
     */
    public String getAdminAuthority() {
        return adminAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_authority
     *
     * @param adminAuthority the value for admin.admin_authority
     *
     * @mbg.generated
     */
    public void setAdminAuthority(String adminAuthority) {
        this.adminAuthority = adminAuthority == null ? null : adminAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_sex
     *
     * @return the value of admin.admin_sex
     *
     * @mbg.generated
     */
    public Integer getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_sex
     *
     * @param adminSex the value for admin.admin_sex
     *
     * @mbg.generated
     */
    public void setAdminSex(Integer adminSex) {
        this.adminSex = adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_phone
     *
     * @return the value of admin.admin_phone
     *
     * @mbg.generated
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_phone
     *
     * @param adminPhone the value for admin.admin_phone
     *
     * @mbg.generated
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_adrress
     *
     * @return the value of admin.admin_adrress
     *
     * @mbg.generated
     */
    public String getAdminAdrress() {
        return adminAdrress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_adrress
     *
     * @param adminAdrress the value for admin.admin_adrress
     *
     * @mbg.generated
     */
    public void setAdminAdrress(String adminAdrress) {
        this.adminAdrress = adminAdrress == null ? null : adminAdrress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_email
     *
     * @return the value of admin.admin_email
     *
     * @mbg.generated
     */
    public String getAdminEmail() {
        return adminEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_email
     *
     * @param adminEmail the value for admin.admin_email
     *
     * @mbg.generated
     */
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail == null ? null : adminEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.modify_time
     *
     * @return the value of admin.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.modify_time
     *
     * @param modifyTime the value for admin.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}