package com.zcz.www.entity;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Team {
    /**
     * Database Column Remarks:
     * 主键ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 团长ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.leader_id
     *
     * @mbg.generated
     */
    private Integer leaderId;

    /**
     * Database Column Remarks:
     * 团队名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_name
     *
     * @mbg.generated
     */
    private String teamName;

    /**
     * Database Column Remarks:
     * 团队区域归属
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_region
     *
     * @mbg.generated
     */
    private String teamRegion;

    /**
     * Database Column Remarks:
     * 团队状态
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_stauts
     *
     * @mbg.generated
     */
    private Integer teamStauts;

    /**
     * Database Column Remarks:
     * 团队人数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.member_num
     *
     * @mbg.generated
     */
    private Integer memberNum;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 修改时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.leader_id
     *
     * @return the value of team.leader_id
     * @mbg.generated
     */
    public Integer getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.leader_id
     *
     * @param leaderId the value for team.leader_id
     * @mbg.generated
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_name
     *
     * @return the value of team.team_name
     * @mbg.generated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_name
     *
     * @param teamName the value for team.team_name
     * @mbg.generated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_region
     *
     * @return the value of team.team_region
     * @mbg.generated
     */
    public String getTeamRegion() {
        return teamRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_region
     *
     * @param teamRegion the value for team.team_region
     * @mbg.generated
     */
    public void setTeamRegion(String teamRegion) {
        this.teamRegion = teamRegion == null ? null : teamRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_stauts
     *
     * @return the value of team.team_stauts
     * @mbg.generated
     */
    public Integer getTeamStauts() {
        return teamStauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_stauts
     *
     * @param teamStauts the value for team.team_stauts
     * @mbg.generated
     */
    public void setTeamStauts(Integer teamStauts) {
        this.teamStauts = teamStauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.member_num
     *
     * @return the value of team.member_num
     * @mbg.generated
     */
    public Integer getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.member_num
     *
     * @param memberNum the value for team.member_num
     * @mbg.generated
     */
    public void setMemberNum(Integer memberNum) {
        this.memberNum = memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.create_time
     *
     * @return the value of team.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.create_time
     *
     * @param createTime the value for team.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.modify_time
     *
     * @return the value of team.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.modify_time
     *
     * @param modifyTime the value for team.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "Team{" +
                "id=" + id +
                ", leaderId=" + leaderId +
                ", teamName='" + teamName + '\'' +
                ", teamRegion='" + teamRegion + '\'' +
                ", teamStauts=" + teamStauts +
                ", memberNum=" + memberNum +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                '}';
    }
}