package com.zcz.www.entity;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Component
public class VolunteerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public VolunteerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameIsNull() {
            addCriterion("volunteer_name is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameIsNotNull() {
            addCriterion("volunteer_name is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameEqualTo(String value) {
            addCriterion("volunteer_name =", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameNotEqualTo(String value) {
            addCriterion("volunteer_name <>", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameGreaterThan(String value) {
            addCriterion("volunteer_name >", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameGreaterThanOrEqualTo(String value) {
            addCriterion("volunteer_name >=", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameLessThan(String value) {
            addCriterion("volunteer_name <", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameLessThanOrEqualTo(String value) {
            addCriterion("volunteer_name <=", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameLike(String value) {
            addCriterion("volunteer_name like", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameNotLike(String value) {
            addCriterion("volunteer_name not like", value, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameIn(List<String> values) {
            addCriterion("volunteer_name in", values, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameNotIn(List<String> values) {
            addCriterion("volunteer_name not in", values, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameBetween(String value1, String value2) {
            addCriterion("volunteer_name between", value1, value2, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerNameNotBetween(String value1, String value2) {
            addCriterion("volunteer_name not between", value1, value2, "volunteerName");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexIsNull() {
            addCriterion("volunteer_sex is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexIsNotNull() {
            addCriterion("volunteer_sex is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexEqualTo(Integer value) {
            addCriterion("volunteer_sex =", value, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexNotEqualTo(Integer value) {
            addCriterion("volunteer_sex <>", value, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexGreaterThan(Integer value) {
            addCriterion("volunteer_sex >", value, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("volunteer_sex >=", value, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexLessThan(Integer value) {
            addCriterion("volunteer_sex <", value, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexLessThanOrEqualTo(Integer value) {
            addCriterion("volunteer_sex <=", value, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexIn(List<Integer> values) {
            addCriterion("volunteer_sex in", values, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexNotIn(List<Integer> values) {
            addCriterion("volunteer_sex not in", values, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexBetween(Integer value1, Integer value2) {
            addCriterion("volunteer_sex between", value1, value2, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerSexNotBetween(Integer value1, Integer value2) {
            addCriterion("volunteer_sex not between", value1, value2, "volunteerSex");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneIsNull() {
            addCriterion("volunteer_phone is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneIsNotNull() {
            addCriterion("volunteer_phone is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneEqualTo(String value) {
            addCriterion("volunteer_phone =", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneNotEqualTo(String value) {
            addCriterion("volunteer_phone <>", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneGreaterThan(String value) {
            addCriterion("volunteer_phone >", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("volunteer_phone >=", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneLessThan(String value) {
            addCriterion("volunteer_phone <", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneLessThanOrEqualTo(String value) {
            addCriterion("volunteer_phone <=", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneLike(String value) {
            addCriterion("volunteer_phone like", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneNotLike(String value) {
            addCriterion("volunteer_phone not like", value, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneIn(List<String> values) {
            addCriterion("volunteer_phone in", values, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneNotIn(List<String> values) {
            addCriterion("volunteer_phone not in", values, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneBetween(String value1, String value2) {
            addCriterion("volunteer_phone between", value1, value2, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerPhoneNotBetween(String value1, String value2) {
            addCriterion("volunteer_phone not between", value1, value2, "volunteerPhone");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailIsNull() {
            addCriterion("volunteer_mail is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailIsNotNull() {
            addCriterion("volunteer_mail is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailEqualTo(String value) {
            addCriterion("volunteer_mail =", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailNotEqualTo(String value) {
            addCriterion("volunteer_mail <>", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailGreaterThan(String value) {
            addCriterion("volunteer_mail >", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailGreaterThanOrEqualTo(String value) {
            addCriterion("volunteer_mail >=", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailLessThan(String value) {
            addCriterion("volunteer_mail <", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailLessThanOrEqualTo(String value) {
            addCriterion("volunteer_mail <=", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailLike(String value) {
            addCriterion("volunteer_mail like", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailNotLike(String value) {
            addCriterion("volunteer_mail not like", value, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailIn(List<String> values) {
            addCriterion("volunteer_mail in", values, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailNotIn(List<String> values) {
            addCriterion("volunteer_mail not in", values, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailBetween(String value1, String value2) {
            addCriterion("volunteer_mail between", value1, value2, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerMailNotBetween(String value1, String value2) {
            addCriterion("volunteer_mail not between", value1, value2, "volunteerMail");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdIsNull() {
            addCriterion("volunteer_pwd is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdIsNotNull() {
            addCriterion("volunteer_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdEqualTo(String value) {
            addCriterion("volunteer_pwd =", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdNotEqualTo(String value) {
            addCriterion("volunteer_pwd <>", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdGreaterThan(String value) {
            addCriterion("volunteer_pwd >", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdGreaterThanOrEqualTo(String value) {
            addCriterion("volunteer_pwd >=", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdLessThan(String value) {
            addCriterion("volunteer_pwd <", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdLessThanOrEqualTo(String value) {
            addCriterion("volunteer_pwd <=", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdLike(String value) {
            addCriterion("volunteer_pwd like", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdNotLike(String value) {
            addCriterion("volunteer_pwd not like", value, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdIn(List<String> values) {
            addCriterion("volunteer_pwd in", values, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdNotIn(List<String> values) {
            addCriterion("volunteer_pwd not in", values, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdBetween(String value1, String value2) {
            addCriterion("volunteer_pwd between", value1, value2, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerPwdNotBetween(String value1, String value2) {
            addCriterion("volunteer_pwd not between", value1, value2, "volunteerPwd");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressIsNull() {
            addCriterion("volunteer_adrress is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressIsNotNull() {
            addCriterion("volunteer_adrress is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressEqualTo(String value) {
            addCriterion("volunteer_adrress =", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressNotEqualTo(String value) {
            addCriterion("volunteer_adrress <>", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressGreaterThan(String value) {
            addCriterion("volunteer_adrress >", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressGreaterThanOrEqualTo(String value) {
            addCriterion("volunteer_adrress >=", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressLessThan(String value) {
            addCriterion("volunteer_adrress <", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressLessThanOrEqualTo(String value) {
            addCriterion("volunteer_adrress <=", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressLike(String value) {
            addCriterion("volunteer_adrress like", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressNotLike(String value) {
            addCriterion("volunteer_adrress not like", value, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressIn(List<String> values) {
            addCriterion("volunteer_adrress in", values, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressNotIn(List<String> values) {
            addCriterion("volunteer_adrress not in", values, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressBetween(String value1, String value2) {
            addCriterion("volunteer_adrress between", value1, value2, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andVolunteerAdrressNotBetween(String value1, String value2) {
            addCriterion("volunteer_adrress not between", value1, value2, "volunteerAdrress");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andStarIsNull() {
            addCriterion("star is null");
            return (Criteria) this;
        }

        public Criteria andStarIsNotNull() {
            addCriterion("star is not null");
            return (Criteria) this;
        }

        public Criteria andStarEqualTo(Integer value) {
            addCriterion("star =", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotEqualTo(Integer value) {
            addCriterion("star <>", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThan(Integer value) {
            addCriterion("star >", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("star >=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThan(Integer value) {
            addCriterion("star <", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThanOrEqualTo(Integer value) {
            addCriterion("star <=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarIn(List<Integer> values) {
            addCriterion("star in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotIn(List<Integer> values) {
            addCriterion("star not in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarBetween(Integer value1, Integer value2) {
            addCriterion("star between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotBetween(Integer value1, Integer value2) {
            addCriterion("star not between", value1, value2, "star");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}