package com.zcz.www.dao;

import com.zcz.www.entity.ActivityUser;
import com.zcz.www.entity.ActivityUserExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ActivityUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    long countByExample(ActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    int insert(ActivityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    int insertSelective(ActivityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    List<ActivityUser> selectByExample(ActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ActivityUser record, @Param("example") ActivityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ActivityUser record, @Param("example") ActivityUserExample example);
}